name: C Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, ubuntu-latest]
        include:
          - os: macos-latest
            run: gcc simulator.c -o simulator-macos
          - os: ubuntu-latest
            run: gcc simulator.c -o simulator-ubuntu
          - os: windows-latest
            run: gcc simulator.c -o simulator

    steps:
    - uses: actions/checkout@v2
    - name: gcc build
      run: ${{ matrix.run }}

  release:
    - depends: build
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          simulator.exe
          simulator-macos
          simulator-ubuntu
