name: C Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          # - os: macos-latest
          #   run: gcc simulator.c -o simulator-macos -ljson-c -lcurl
          # - os: ubuntu-latest
          #   run: gcc simulator.c -o simulator-ubuntu -ljson-c -lcurl
          - os: windows-latest
            run: gcc simulator.c -o simulator -ljson-c -lcurl

    steps:
    - uses: actions/checkout@v2
    - name: gcc build
      run: ${{ matrix.run }}
